### ISSUE TITLE
Image size functionality breaks on external images

### ISSUE THREAD

**Issue by Jay-Salisbury** [ruanyf/markdown-it-image-lazy-loading#3]
It would be nice if this would either pull the image size from externally hosted images or ignore them to avoid crashing

**Comment by ruanyf** [comment]
It is impossible to get the size of external images without downloading them.

**Comment by gerwitz** [comment]
I have a lot of absolute URLs, it would be great to have the option to specify the published URL root so those can be transformed to local paths instead of throwing an error.

And, more generally, recognize URLs and skip them or log only warnings rather than throwing exceptions.
